{% set name = "cppdap" %}
{% set version = "1.58.0-a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/google/{{ name }}/releases/download/{{ version }}/cppdap-{{ version }}.tar.gz
  url: https://github.com/google/{{ name }}/archive/refs/tags/dap-{{ version }}.tar.gz
  sha256: 5d35ca5db78570b6bef698e3365f79bd82a4f78e8393546387f78d7bdb2a2a08
  # url: https://github.com/google/{{ name }}/archive/v{{ version }}.tar.gz

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make            # [unix]
    - patch           # [not win]
    - m2-patch        # [win]
  host:
  run:

test:
  files:
  requires:
  commands:
    - cmake --version

about:
  home: https://github.com/google/cppdap
  summary: 'A C++11 implementation of DAP'
  description: |
    cppdap is a C++11 library ("SDK") implementation of the Debug Adapter Protocol, 
    providing an API for implementing a DAP client or server. 
    cppdap provides C++ type-safe structures for the full DAP specification,
    and provides a simple way to add custom protocol messages.
  license: Apache-2
  license_family: Apache
  license_file: LICENSE.txt
  dev_url: https://github.com/google/cppdap

extra:
  recipe-maintainers:
    - phreed
